---
coverage:
  status:
    project:
      default:
        # Set non-blocking status checks
        informational: true
    patch:
      default:
        # Set non-blocking status checks
        informational: true
 
