name: 'notation-azure-kv E2E testing'
description: 'This is a test action for testing the notation-azure-kv plugin on mltiple platforms.'
inputs:
  pluginDownloadURL:
    description: 'Where to download the plugin'
    required: true
  pluginChecksum:
    description: 'The checksum of the plugin'
    required: true
runs:
  using: "composite"
  steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: setup Notation CLI
      uses: notaryproject/notation-action/setup@v1
      with:
        version: 1.0.0
    - name: self-signed certificate 
      uses: notaryproject/notation-action/sign@v1
      with:
        plugin_name: azure-kv
        plugin_url: ${{ inputs.pluginDownloadURL }}
        plugin_checksum: ${{ inputs.pluginChecksum }}
        key_id: https://acrci-test-kv.vault.azure.net/keys/self-signed-pkcs12/70747b2064c0488e936eba7a29acc4c6
        target_artifact_reference: localhost:5000/hello-world:v1
        signature_format: cose
        plugin_config: 'self_signed=true'