name: Release notation-azure-kv

on:
  push:
    tags:
      - 'v*'

# Contents write required for release PRs
permissions:
  contents: write

jobs:
  build:
    strategy:
      max-parallel: 3
      matrix:
        runtime: ["linux-x64", "linux-arm64", "win-x64", "osx-x64", "osx-arm64"]
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name : Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build .NET project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./scripts/build.sh "${GITHUB_REF_NAME}" ${{ matrix.runtime }}
      - name: Upload ${{ matrix.runtime }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.runtime }}
          path: ${{ github.workspace }}/bin/artifacts/*
          retention-days: 1
  macos_codesign:
    strategy:
      matrix:
        runtime: ["osx-x64", "osx-arm64"]
    name: Codesign
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.runtime }}
          path: ${{ github.workspace }}/artifacts/${{ matrix.runtime }}
      - name: Codesign
        run: bash ./scripts/codesign.sh ${{ matrix.runtime }}
      - name: Upload ${{ matrix.runtime }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.runtime }}
          path: ${{ github.workspace }}/artifacts/*
          retention-days: 1
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [macos_codesign]
    steps:
      - name: Download linux-x64 artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-x64
      - name: Download linux-arm64 artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-arm64
      - name: Download win-x64 artifact
        uses: actions/download-artifact@v3
        with:
          name: win-x64
      - name: Download osx-x64 artifact
        uses: actions/download-artifact@v3
        with:
          name: osx-x64
      - name: Download osx-arm64 artifact
        uses: actions/download-artifact@v3
        with:
          name: osx-arm64
      - name: Create release
        run: bash ./scripts/release.sh "${GITHUB_REF_NAME}"
