name: test

on: [pull_request]

jobs:
  lint:
    strategy:
      matrix:
        go-version: ['1.20']

    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --fast=false

  build:
    strategy:
      matrix:
        go-version: ['1.20']

    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Run unit tests
      run: go test ./...
    - name: Build testing
      run: make build
