name: test

on: [pull_request]

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.46.0
        args: --fast=false

  unit-test:
    name: "Unit Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Run unit tests
      run: go test ./...
